apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  namespace: sandbox
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: <your-storage-class>   # set this if the cluster has no default StorageClass
