apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ch-data
  namespace: sandbox
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  # storageClassName: <your-storage-class>
