apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ch-logs
  namespace: sandbox
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # storageClassName: <your-storage-class>
